---
- name: Ensure rtorrent is installed
  become: yes
  pacman:
    name: rtorrent
    state: present

- name: Ensure aria2 is installed
  become: yes
  pacman:
    name: aria2
    state: present

- name: Links torrent to magnet
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/local/bin/magnet2torrent.sh"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.local/bin/magnet2torrent.sh"
    state: link
    force: yes

- name: Ensure rtorrent config
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/config/rtorrent/rtorrent.rc"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.config/rtorrent/rtorrent.rc"
    state: link
    force: yes
