---
- name: Install upower
  pacman:
    name: upower
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Install upower
  apt:
    name: upower
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"
