- name: Install Rust
  pacman:
    name: rust
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Install Rust
  apt:
    name: rust-all
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Make sure the Cargo config/share folder exists
  ansible.builtin.file:
    path: "{{ lookup( 'env', 'HOME' ) }}/.local/share/cargo"
    state: directory
    mode: '0700'

- name: Links config file for Cargo
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/local/share/cargo/config"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.local/share/cargo/config"
    state: link
    force: yes
