local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, { desc = "Fuzzy find files" })
vim.keymap.set('n', '<C-p>', builtin.git_files, { desc = "Fuzzy find files in git" })
vim.keymap.set('n', '<leader>fi', builtin.git_files, { desc = "Fuzzy find files in git" })
vim.keymap.set('n', '<leader>fg', builtin.live_grep, { desc = "Grep for file contents" })
vim.keymap.set('n', '<leader>fb', builtin.buffers, { desc = "Find buffers" })
vim.keymap.set('n', '<leader>fh', builtin.help_tags, { desc = "Fuzzy find for help tags" })
