---
- name: Installs the Mozilla Firefox Browser
  pacman:
    name: firefox
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Installs the Mozilla Firefox Browser
  apt:
    name: firefox-esr
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"
