---
- name: Install "bash-language-server" node package.
  npm:
    name: bash-language-server
    global: yes
  become: yes

- name: Install shellcheck
  pacman:
    name: shellcheck
    state: present
  become: true

- name: Update profile file
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/profile"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.profile"
    state: link
    force: yes
