---
- name: Install "bash-language-server" node package.
  npm:
    name: bash-language-server
    global: yes
  become: yes

- name: Install shellcheck
  pacman:
    name: shellcheck
    state: present
  become: true

