---
- name: Installs mpv player
  pacman:
    name: mpv
    state: present
  become: true

- name: Links config file for mpv
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/config/mpv"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.config/mpv"
    state: link
    force: yes
