---
- name: Installs mpv player
  pacman:
    name: mpv
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Installs mpv player
  apt:
    name: mpv
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Links config file for mpv
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/config/mpv"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.config/mpv"
    state: link
    force: yes
