# tasks to complete before running roles
- hosts: all
  connection: local
  tags: always
  become: true
  pre_tasks:
    - name: pre-run | Update package cache (Arch)
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"
    - name: pre-run | Update package cache (Debian)
      tags: always
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

- hosts: all
  tags: base
  connection: local
  roles:
    - base
    - node
    - bash # It requires node first to install the LS
    - gpg
    - nvim
    - python
    - reflector
    - starship
    - zsh

- hosts: laptop
  tags: laptop
  connection: local
  roles:
    - upower

- hosts: workstation
  tags: workstation
  connection: local
  roles:
    - alacritty
    - audio
    - asdf
    - aws
    - bluetooth
    - bspwm
    - dunst
    # - fstrim
    - firefox
    - google-chrome
    # - ntp
    - polybar
    # - powertop
    # - rust
    - suckless
    - task
    # - terraform
    # - vconsole
    - wifi
    - xorg
    # - zathura
    # - spotify
    - work
    # - mikrotik
    # - gtk
    # - kitty
    # - latex
    # - newsboat
    # - mpv
    # - mpd
    # - etckeeper
      #- dropbox

- hosts: vortan
  tags: vortan
  connection: local
  roles:
    #- aws
    #- k8s
    - xps9750
    #- wireguard

- hosts: dutchman
  tags: dutchman
  connection: local
  roles:
    - dutchman
    - raspberrypi-tools

- hosts: g14
  connection: local
  roles:
    - amdgpu
    - certificado-digital
    - g14
    - nvidia
    - torrent
    - wireguard

