- hosts: localhost
  connection: local
  become: true

  roles:
    - kewlfft.aur
  
  pre_tasks:
    - name: pre-run | update package cache (arch)
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

  tasks:
    - include: tasks/base.yaml
    - include: tasks/zsh.yaml
    - include: tasks/nvim.yaml
