# tasks to complete before running roles
- hosts: all
  connection: local
  tags: always
  become: true
  pre_tasks:
    - name: pre-run | update package cache (arch)
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

- hosts: all
  tags: base
  connection: local
  become: true
  roles:
    - base
    - starship

- hosts: workstation
  tags: workstation
  connection: local
  become: true
  roles:
    - kitty

# tasks:
#     - include: tasks/nvim.yaml
#     - include: tasks/terraform.yaml
#     - include: tasks/tdrop.yaml
#     - include: tasks/zsh.yaml
#     - include: tasks/starship.yaml
