- hosts: localhost
  connection: local

  roles:
    - kewlfft.aur
  
  pre_tasks:
    - name: pre-run | update package cache (arch)
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"
      become: true
      become_user: root

  tasks:
    - include: tasks/base.yaml
    - include: tasks/nvim.yaml
    - include: tasks/terraform.yaml
    - include: tasks/zsh.yaml
