# tasks to complete before running roles
- hosts: all
  connection: local
  tags: always
  become: true
  pre_tasks:
    - name: pre-run | update package cache (arch)
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

- hosts: all
  tags: base
  connection: local
  become: true
  roles:
    - base
    - node
    - bash # It requires node first to install the LS
    - nvim
    - python
    - starship
    - zsh

- hosts: workstation
  tags: workstation
  connection: local
  become: true
  roles:
    - kitty
    - terraform

