---
- name: Installs terminus font
  kewlfft.aur.aur:
    use: paru
    name: terminus-font
  when: ansible_distribution == "Archlinux"

- name: Install terminus font
  apt:
    name:
      - fonts-terminus
      - fonts-terminus-otb
      - xfonts-terminus
      - xfonts-terminus-dos
      - xfonts-terminus-oblique
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Configures vconsole
  ansible.builtin.copy:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/etc/vconsole.conf"
    dest: /etc/vconsole.conf
    owner: root
    group: root
    mode: '0644'
  become: true
