---
- name: Install Xorg complete system
  pacman:
    name: xorg
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Install Xinit
  pacman:
    name: xorg-xinit
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Install arandr
  pacman:
    name: arandr
    state: present
  become: true
  when: ansible_distribution == "Archlinux"


- name: Install xdotool
  pacman:
    name: xdotool
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Install xdo
  pacman:
    name: xdo
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Install light to control screen backlight
  pacman:
    name: light
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Install nerdfonts Cascadia Code
  pacman:
    state: present
    name: community/ttf-cascadia-code-nerd
  become: true
  when: ansible_distribution == "Archlinux"

- name: Install nerdfonts Fantasque
  pacman:
    state: present
    name: community/ttf-fantasque-nerd
  become: true
  when: ansible_distribution == "Archlinux"

- name: Install nerdfonts Fira Code
  pacman:
    state: present
    name: nerd-fonts-fira-code
  become: true
  when: ansible_distribution == "Archlinux"

- name: Install nerdfonts Hack
  pacman:
    state: present
    name: community/ttf-hack-nerd
  become: true
  when: ansible_distribution == "Archlinux"

- name: Install nerdfonts Jetbrains Mono
  pacman:
    state: present
    name: community/ttf-jetbrains-mono-nerd
  become: true
  when: ansible_distribution == "Archlinux"

- name: Install nerdfonts Overpass
  pacman:
    state: present
    name: community/otf-overpass-nerd
  become: true
  when: ansible_distribution == "Archlinux"

- name: Install nerdfonts Roboto Mono
  pacman:
    state: present
    name: community/ttf-roboto-mono-nerd
  become: true
  when: ansible_distribution == "Archlinux"

- name: Install nerdfonts Source Code Pro
  pacman:
    state: present
    name: community/ttf-sourcecodepro-nerd
  become: true
  when: ansible_distribution == "Archlinux"

- name: Install nerdfonts Terminus
  pacman:
    state: present
    name: community/ttf-terminus-nerd
  become: true
  when: ansible_distribution == "Archlinux"

- name: Install nerdfonts Ubuntu Mno
  pacman:
    state: present
    name: community/ttf-ubuntu-mono-nerd
  become: true
  when: ansible_distribution == "Archlinux"

- name: Install noto-fonts-emoji
  pacman:
    name: noto-fonts-emoji
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Install tff-dejavu (needed for gtop)
  pacman:
    name: ttf-dejavu
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Install JoyPixels emoji font
  pacman:
    name: ttf-joypixels
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Install symbola ttf emoji font
  kewlfft.aur.aur:
    use: paru
    name: ttf-symbola
  when: ansible_distribution == "Archlinux"

- name: Install feh
  pacman:
    name: feh
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Links switch-layout script
  ansible.builtin.file:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/local/bin/switch-layout.sh"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.local/bin/switch-layout.sh"
    state: link
    force: yes

- name: Make sure the config X11 folder exists
  ansible.builtin.file:
    path: "{{ lookup( 'env', 'HOME' ) }}/.config/X11"
    state: directory
    mode: '0755'

- name: Links Xresources file
  ansible.builtin.file:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/config/X11/Xresources"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.config/X11/xresources"
    state: link
    force: yes

- name: Install colorpicker
  kewlfft.aur.aur:
    use: paru
    name: colorpicker
  when: ansible_distribution == "Archlinux"

