---
- name: Collection of tools like iwlist
  pacman:
    name: wireless_tools
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Installs iwd wifi deamon
  apt:
    name: iwd
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Copy iwd config file
  ansible.builtin.copy:
    src: main.conf
    dest: /etc/iwd/main.conf
    mode: 0644
    owner: root
    group: root
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Activate iwd systemd service
  ansible.builtin.systemd:
    state: disabled
    enabled: false
    name: iwd.service
  become: true
  when: ansible_facts['os_family'] == "Debian"
