---
- name: Install which
  pacman:
    name: which
    state: present
    
- name: Install basic network utils such as hostname
  pacman:
    name: inetutils
    state: present

- name: Install shellcheck
  pacman:
    name: shellcheck
    state: present
