---
- name: Install BSPWM
  pacman:
    name: bspwm
    state: present
  become: true
  
- name: Links config file for BSPWM
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/config/bspwm"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.config/bspwm"
    state: link
    force: yes
    
- name: Links monitor script to manage desktops when using connecting monitors
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/local/bin/monitor.sh"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.local/bin/monitor.sh"
    state: link
    force: yes
