---
- name: Allows user in video group to change keyboard backlight in g14 backlight
  ansible.builtin.copy:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/etc/udev/rules.d/asus-keyboard.rules"
    dest: /etc/udev/rules.d/asus-keyboard.rules
    owner: root
    group: root
    mode: '0644'
  become: true
  
- name: Links asus brightness configuration
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/local/bin/asus_keyboard_backlight.sh"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.local/bin/asus_keyboard_backlight.sh"
    state: link
    force: yes

- name: Install asus control tool
  aur:
    use: paru
    name:
      - asus-nb-ctrl-git
      
- name: Activate asusd service
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: asusd
  become: true

- name: Update the asusd service configuration
  ansible.builtin.copy:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/etc/asusd/asusd.conf"
    dest: /etc/asusd/asusd.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  
- name: Activate asus-notify service
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: asus-notify.service
    scope: user
  
- name: Links asus profile change
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/local/bin/asus_profile.sh"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.local/bin/asus_profile.sh"
    state: link
    force: yes

- name: Add asus monitor size configuration
  become: yes
  ansible.builtin.copy:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/etc/X11/xorg.conf.d/40-monitor-asus-g14.conf"
    dest: "/etc/X11/xorg.conf.d/40-monitor-asus-g14.conf"
    owner: root
    group: root
    mode: '0644'

- name: Add asus keyboard lights save/restore script
  become: yes
  ansible.builtin.copy:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/usr/local/bin/g14-kbd-backlight-suspend.sh"
    dest: "/usr/local/bin/g14-kbd-backlight-suspend.sh"
    owner: root
    group: root
    mode: '0755'

- name: Add turn off keyboard lights service at suspend
  become: yes
  ansible.builtin.copy:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/etc/systemd/system/g14_suspend@.service"
    dest: "/etc/systemd/system/g14_suspend@.service"
    owner: root
    group: root
    mode: '0644'

- name: Add restore keyboard lights service at resume
  become: yes
  ansible.builtin.copy:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/etc/systemd/system/g14_resume@.service"
    dest: "/etc/systemd/system/g14_resume@.service"
    owner: root
    group: root
    mode: '0644'

- name: Activate suspend lights
  ansible.builtin.systemd:
    state: stopped
    enabled: yes
    name: g14_suspend@david 
  become: true

- name: Activate restore lights
  ansible.builtin.systemd:
    state: stopped
    enabled: yes
    name: g14_resume@david 
  become: true

- name: Links Xresources file for G14
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/X/Xresources.g14"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.Xresources"
    state: link
    force: yes
