---
- name: Installs K9s
  pacman:
    name: k9s
    state: present
  become: true

- name: Make sure k9s config folder exists
  ansible.builtin.file:
    path: "{{ lookup( 'env', 'HOME' ) }}/.config/k9s"
    state: directory
    mode: '0755'

- name: Copy color scheme file for K9s
  ansible.builtin.copy:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/config/k9s/skin.yml"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.config/k9s/skin.yml"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: '0644'
