---
- name: Install
  apt:
    name: printer-driver-all
    state: latest
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Install CUPS
  apt:
    name: cups
    state: latest
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Install CUPS
  apt:
    name: cups-browsed
    state: latest
  become: true
  when: ansible_facts['os_family'] == "Debian"

