---
- name: Install nvidia kernel modules
  pacman:
    name: nvidia
    state: present
  become: true

- name: Install nvidia-utils
  pacman:
    name: nvidia-utils
    state: present
  become: true
  
- name: Configures nvidia driver
  ansible.builtin.copy:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/etc/modprobe.d/nvidia.conf"
    dest: /etc/modprobe.d/nvidia.conf
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Disable nouveau driver
  ansible.builtin.copy:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/etc/modprobe.d/nouveau.conf"
    dest: /etc/modprobe.d/nouveau.conf
    owner: root
    group: root
    mode: '0644'
  become: true
