#! /bin/sh

# Launch shortcut daemon
sxhkd &

# Launch Polybar
~/.config/polybar/launch.sh

# Set background image
feh --bg-fill /home/david/Pictures/wallpapers/20190127_delta-del-ebro__DGP8946_0007.jpg &

# Adding pulseaudio service startup
/usr/bin/start-pulseaudio-x11 & 

# Adding transparency
compton -f &

# Bluetooth Applet
blueman-applet &

bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10 

bspc config border_width         2
bspc config window_gap          12

bspc config top_padding          28
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

