---
- name: Ensure imagemagick dependency is installed
  pacman:
    name: imagemagick
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Installs fprintd
  pacman:
    name: fprintd
    state: present
  become: true
  when: ansible_distribution == "Archlinux"
