# For Arch systems
- name: Installs Gruvbox Material icon theme
  kewlfft.aur.aur:
    use: paru
    name: gruvbox-material-icon-theme-git
  when: ansible_distribution == "Archlinux"

- name: Installs Gruvbox Material GTK theme
  kewlfft.aur.aur:
    use: paru
    name: gruvbox-material-gtk-theme-git
  when: ansible_distribution == "Archlinux"

# For debian systems
- name: Install the Murrine theme required by the Gruvbox theme
  become: true
  apt:
    name: gtk2-engines-murrine
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Ensure XDG icons folder exists
  ansible.builtin.file:
    path: "{{ lookup( 'env', 'HOME' ) }}/.local/share/icons"
    state: directory
    mode: '0755'

- name: Clone Gruvbox Material Icon and Theme
  ansible.builtin.git:
    repo: https://github.com/TheGreatMcPain/gruvbox-material-gtk.git
    dest: "{{ lookup( 'env', 'HOME' ) }}/.local/share/themes/gruvbox-material-gtk"
  when: ansible_facts['os_family'] == "Debian"

- name: Links Gruvbox Material Icon Theme
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/.local/share/themes/gruvbox-material-gtk/icons/Gruvbox-Material-Dark"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.local/share/icons/Gruvbox-Material-Dark"
    state: link
    force: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Links Gruvbox Material GTK Theme HIDPI
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/.local/share/themes/gruvbox-material-gtk/themes/Gruvbox-Material-Dark-HIDPI"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.local/share/themes/Gruvbox-Material-Dark-HIDPI"
    state: link
    force: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Links Gruvbox Material GTK Theme
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/.local/share/themes/gruvbox-material-gtk/themes/Gruvbox-Material-Dark"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.local/share/themes/Gruvbox-Material-Dark"
    state: link
    force: yes
  when: ansible_facts['os_family'] == "Debian"

# For everybody
- name: Links config file for GTK-3.0
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/config/gtk-3.0"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.config/gtk-3.0"
    state: link
    force: yes

- name: Links config file for GTK-2.0
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/config/gtk-2.0"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.config/gtk-2.0"
    state: link
    force: yes

