---
# For Arch Linux
- name: Installs Spotify
  kewlfft.aur.aur:
    use: paru
    name: spotify
  when: ansible_distribution == "Archlinux"

# For debian systems
- name: Copy google chrome repo
  ansible.builtin.copy:
    src: spotify.list
    dest: /etc/apt/sources.list.d/spotify.list
    mode: 0644
    owner: root
    group: root
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Install spotify
  become: true
  apt:
    name: spotify-client
    state: present
  when: ansible_facts['os_family'] == "Debian"

