---
- name: Installs pulseaudio
  pacman:
    name: pulseaudio
    state: present
  become: true

- name: Install pulseaudio-alsa
  pacman:
    name: pulseaudio-alsa
    state: present
  become: true

- name: Install necessary LDAC libs
  pacman:
    name: libldac
    state: present
  become: true
  
- name: Install necessary LDAC libs
  pacman:
    name: pavucontrol
    state: present
  become: true
  
- name: Installs extra bluetooth codecs
  aur:
    use: paru
    name:
      - pulseaudio-modules-bt

