---
- name: Links AWS assume role script
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/local/bin/aws_assume_role.sh"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.local/bin/aws_assume_role"
    state: link
    force: yes

- name: Links AWS ssm script
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/local/bin/ssm.sh"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.local/bin/ssm"
    state: link
    force: yes

- name: Installs Amazon ECR Credential Helper
  kewlfft.aur.aur:
    use: paru
    name: amazon-ecr-credential-helper
  when: ansible_distribution == "Archlinux"

- name: Installs Amazon ECR Credential Helper
  become: true
  apt:
    name: amazon-ecr-credential-helper
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Ensure AWS data folder exists
  ansible.builtin.file:
    path: "{{ lookup( 'env', 'HOME' ) }}/.local/share/aws"
    state: directory
    mode: '0700'

- name: Ensure AWS config folder exists
  ansible.builtin.file:
    path: "{{ lookup( 'env', 'HOME' ) }}/.config/aws"
    state: directory
    mode: '0700'
