- name: Install Kitty
  pacman:
    name: kitty
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Install Kitty
  apt:
    name: kitty
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Links Kitty configuration file
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/kitty"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.config/kitty"
    state: link
    force: yes
