- name: Install Kitty
  pacman:
    name: kitty
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Install Kitty
  apt:
    name: kitty
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"
