- name: Install Kitty
  pacman:
    name: kitty
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Install Kitty
  apt:
    name: kitty
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Make sure Kitty config folder exists
  ansible.builtin.file:
    path: "{{ lookup( 'env', 'HOME' ) }}/.config/kitty"
    state: directory
    mode: '0750'

- name: Links Kitty configuration file
  file:
    src: "{{ lookup( 'env', 'ROOTDIR' ) }}/files/config/kitty/kitty.conf"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.config/kitty/kitty.conf"
    state: link
    force: yes

- name: Links Kitty configuration file
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/kitty"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.config/kitty"
    state: link
    force: yes
