---
# For Arch Linux systems
- name: Installs Terraform Language Server
  kewlfft.aur.aur:
    use: paru
    name: terraform-ls
  when: ansible_distribution == "Archlinux"

# For debian systems
- name: Enable the Hashicorp repo
  ansible.builtin.copy:
    src: hashicorp.list
    dest: /etc/apt/sources.list.d/hashicorp.list
    mode: 0644
    owner: root
    group: root
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Install packer
  become: true
  apt:
    name: packer
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Install terraform-ls
  become: true
  apt:
    name: terraform-ls
    state: present
  when: ansible_facts['os_family'] == "Debian"
