---
- name: Links git-sync command
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/local/bin/git-sync.sh"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.local/bin/git-sync.sh"
    state: link
    force: yes

- name: Links git-sync-on-inotify command
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/local/bin/git-sync-on-inotify.sh"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.local/bin/git-sync-on-inotify.sh"
    state: link
    force: yes

- name: Links git-sync SystemD service
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/config/systemd/user/git-sync@.service"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.config/systemd/user/git-sync@.service"
    state: link
    force: yes

- name: Enable git-sync service for Neorg
  ansible.builtin.systemd:
    name: git-sync@neorg
    state: started
    enabled: yes
    scope: user
