---
- name: Install dunst notifier
  pacman:
    name: dunst
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Install dunst notifier
  apt:
    name: dunst
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Install icon theme for dunst
  pacman:
    name: adwaita-icon-theme
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Install icon theme for dunst
  apt:
    name: adwaita-icon-theme
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Links config file for dunst
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/config/dunst"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.config/dunst"
    state: link
    force: yes
