---
- name: Install polybar
  kewlfft.aur.aur:
    use: paru
    name: polybar
  when: ansible_distribution == "Archlinux"

- name: Install polybar
  apt:
    name: polybar
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Links config file for Polybar
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/config/polybar"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.config/polybar"
    state: link
    force: yes
