---
- name: Installs slack-desktop
  kewlfft.aur.aur:
    use: paru
    name: slack-desktop

- name: Installs zoom
  kewlfft.aur.aur:
    use: paru
    name: zoom

- name: Installs openfortivpn
  pacman:
    name: openfortivpn
    state: present
  become: true

- name: Installs jdk-openjdk for Okta
  pacman:
    name: jdk-openjdk
    state: present
  become: true

- name: Installs kubectl
  pacman:
    name: kubectl
    state: present
  become: true

- name: Install kubectx
  pacman:
    name: kubectx
    state: present
  become: true

- name: Install kubens
  pacman:
    name: kubens
    state: present
  become: true
