---
- name: Installs slack-desktop
  kewlfft.aur.aur:
    use: paru
    name: slack-desktop
  when: ansible_distribution == "Archlinux"

- name: Installs slack-desktop Debian missing deps
  apt:
    name: libappindicator3-0.1-cil
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"

# TODO It needs to be manually installed
# - name: Installs slack-desktop
#   apt:
#     deb: https://downloads.slack-edge.com/releases/linux/4.21.1/prod/x64/slack-desktop-4.21.1-amd64.deb
#     dpkg_options: 'force-depends'
#   become: true
#   when: ansible_facts['os_family'] == "Debian"

- name: Installs zoom
  kewlfft.aur.aur:
    use: paru
    name: zoom
  when: ansible_distribution == "Archlinux"

- name: Installs zoom Debian missing dependencies
  apt:
    name:
      - mailcap
      - libgl1-mesa-glx
      - libglx-mesa0
      - ibus
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Installs zoom
  apt:
    deb: https://zoom.us/client/latest/zoom_amd64.deb
    dpkg_options: 'force-depends'
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Installs Microsoft Teams
  kewlfft.aur.aur:
    use: paru
    name: teams
  when: ansible_distribution == "Archlinux"

- name: Installs Microsoft Teams
  apt:
    name: teams
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Installs openfortivpn
  pacman:
    name: openfortivpn
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Installs openfortivpn
  apt:
    name: openfortivpn
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Installs jdk-openjdk for Okta
  pacman:
    name: jdk-openjdk
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Installs jdk-openjdk for Okta
  apt:
    name: openjdk-11-jdk
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Installs kubectl
  pacman:
    name: kubectl
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Installs kubectl
  apt:
    name: kubernetes-client
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Install kubectx
  pacman:
    name: kubectx
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Installs kubectx
  apt:
    name: kubectx
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Install kubens
  pacman:
    name: kubens
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Get the latests draw.io release
  shell: curl -s https://api.github.com/repos/jgraph/drawio-desktop/releases/latest | grep browser_download_url | grep '\.deb' | cut -d '"' -f 4
  register: drawio_version
  when: ansible_facts['os_family'] == "Debian"

- name: Install latest version of draw.io
  apt:
    deb: '{{ drawio_version.stdout }}'
  become: true
  when: ansible_facts['os_family'] == "Debian"

