---
- name: Installs Zathura PDF reader
  pacman:
    name: zathura
    state: present
  become: true

- name: Install Zathura PDF plugin
  pacman:
    name: zathura-pdf-mupdf
    state: present
  become: true
