---
- name: Installs powertop
  pacman:
    name: powertop
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Installs powertop
  apt:
    name: powertop
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"
