---
- name: Installs mpd latest version
  pacman:
    name: mpd
    state: present
  become: true
  
- name: Installs mpc latest version
  pacman:
    name: mpc
    state: present
  become: true

- name: Links config file for mpd
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/config/mpd"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.config/mpd"
    state: link
    force: yes

- name: Make sure log folder exists for mpd
  ansible.builtin.file:
    path: "{{ lookup( 'env', 'HOME' ) }}/.local/runtime/mpd"
    state: directory
    mode: '0755'

- name: Make sure playlists folder exists for mpd
  ansible.builtin.file:
    path: "{{ lookup( 'env', 'HOME' ) }}/.local/share/mpd/playlists"
    state: directory
    mode: '0755'

- name: Ensure official ncmpcpp package is not installated
  pacman:
    name: ncmpcpp
    state: absent
  become: true

- name: Install the NCurses Music Player Client Plus Plus ncmpcpp
  aur:
    use: paru
    name:
      - ncmpcpp-git
  
- name: Wrapper for ncmpcpp
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/local/bin/player.sh"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.local/bin/player"
    state: link
    force: yes

- name: Make sure lyrics folder exists for ncmpcpp
  ansible.builtin.file:
    path: "{{ lookup( 'env', 'HOME' ) }}/.cache/ncmpcpp"
    state: directory
    mode: '0755'

- name: Installs beets
  pacman:
    name: beets
    state: present
  become: true

- name: Ensure beets music folder
  ansible.builtin.file:
    path: "{{ lookup( 'env', 'HOME' ) }}/Music/beets"
    state: directory
    mode: '0755'

- name: Ensure beets db folder exists
  ansible.builtin.file:
    path: "{{ lookup( 'env', 'HOME' ) }}/Dropbox/beets"
    state: directory
    mode: '0755'

- name: Ensure beets config folder exists
  ansible.builtin.file:
    path: "{{ lookup( 'env', 'HOME' ) }}/.config/beets"
    state: directory
    mode: '0755'

- name: Links beets configuration file
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/config/beets/config.yaml"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.config/beets/config.yaml"
    state: link
    force: yes

- name: Ensure pylast is installed
  pacman:
    name: python-pylast
    state: present
  become: true

- name: Installs mpd-notification
  aur:
    use: paru
    name:
      - mpd-notification

- name: Links beets configuration file
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/config/mpd-notification.conf"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.config/mpd-notification.conf"
    state: link
    force: yes

# - name: Activate mpd-notification service for user 
#   ansible.builtin.systemd:
#     state: started
#     enabled: yes
#     name: mpd-notification
#     scope: user

- name: Installs ueberzug for displaying images in terminal
  pacman:
    name: ueberzug
    state: present
  become: true

- name: Installs tmux for displaying images in terminal
  pacman:
    name: tmux
    state: present
  become: true
  
- name: Installs inotify-tools for displaying images in terminal
  pacman:
    name: inotify-tools
    state: present
  become: true

- name: Installs ffmpeg for displaying images in terminal
  pacman:
    name: ffmpeg
    state: present
  become: true

- name: Links config file for ncmpcpp
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/config/ncmpcpp"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.config/ncmpcpp"
    state: link
    force: yes
