---
- name: Install node 
  pacman:
    name: nodejs
    state: present
  become: yes

- name: Update npm configuration
  ansible.builtin.script: configure_npm.sh
    
- name: Install npm 
  pacman:
    name: npm 
    state: present
  become: yes
