---
- name: Install node
  apt:
    name: nodejs
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Update npm configuration
  ansible.builtin.script: configure_npm.sh

- name: Install npm
  pacman:
    name: npm
    state: present
  become: true
  when: ansible_distribution == "Archlinux"
