---
- name: Ensure snapd is installed for Mikrotik Winbox
  kewlfft.aur.aur:
    use: paru
    name: snapd
  when: ansible_distribution == "Archlinux"

- name: Ensure snapd is installed for Mikrotik Winbox
  apt:
    name: snapd
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Activate Snapd systemd service
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: snapd.socket
  become: true

- name: Links snapd folder to /snap
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
    force: yes
  become: true
  when: ansible_distribution == "Archlinux"

- name: Install Winbox as an Snap package
  community.general.snap:
    name: winbox
    state: present
  become: true
