---
- name: Installs taskwarrior
  pacman:
    name: task
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Installs taskwarrior
  apt:
    name: taskwarrior
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Make sure task folder exists
  ansible.builtin.file:
    path: "{{ lookup( 'env', 'HOME' ) }}/.local/share/task"
    state: directory
    mode: '0755'

- name: Make sure task certs folder exists
  ansible.builtin.file:
    path: "{{ lookup( 'env', 'HOME' ) }}/.local/share/task/certs"
    state: directory
    mode: '0700'

- name: Make sure task hooks folder exists
  ansible.builtin.file:
    path: "{{ lookup( 'env', 'HOME' ) }}/.local/share/task/hooks"
    state: directory
    mode: '0700'

- name: Ensure taskwarrior is configured
  template:
    src: taskrc.j2
    dest: ~/.config/taskrc

- name: Add colorscheme
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/config/taskwarrior"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.config/taskwarrior"
    state: link
    force: yes

- name: Add Taskwarrior sync hook
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/local/share/task/hooks/on-exit-sync.sh"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.local/share/task/hooks/on-exit-sync.sh"
    state: link
    force: yes
