---
- name: Installs taskwarrior
  pacman:
    name: task
    state: present
  become: yes

- name: Make sure task folder exists
  ansible.builtin.file:
    path: "{{ lookup( 'env', 'HOME' ) }}/.local/share/task"
    state: directory
    mode: '0755'

