#!/bin/bash
XDG_CONFIG_HOME="${HOME}/.config"
XDG_CACHE_HOME="${HOME}/.cache"
XDG_DATA_HOME="${HOME}/.local/share"
XDG_STATE_HOME="${HOME}/.local/state"
export XDG_CONFIG_HOME
export XDG_CACHE_HOME
export XDG_DATA_HOME
export XDG_STATE_HOME

# Typical programs
EDITOR="nvim"
export EDITOR
TERMINAL="st"
export TERMINAL
BROWSER="firefox"
export BROWSER

# ASDF DATA DIR
ASDF_DATA_DIR="${XDG_DATA_HOME}/asdf"
export ASDF_DATA_DIR

# ASDF DEFAULT PYTHON PACKAGES FILE
ASDF_PYTHON_DEFAULT_PACKAGES_FILE="${XDG_CONFIG_HOME}/asdf/default-python-packages"
export ASDF_PYTHON_DEFAULT_PACKAGES_FILE

# ASDF DEFAULT NPM PACKAGES FILE
ASDF_NPM_DEFAULT_PACKAGES_FILE="${XDG_CONFIG_HOME}/asdf/default-npm-packages"
export ASDF_NPM_DEFAULT_PACKAGES_FILE

# Cuda cacha folder
CUDA_CACHE_PATH="${XDG_CACHE_HOME}/nv"
export CUDA_CACHE_PATH

# Docker to follow XDG config
DOCKER_CONFIG="${XDG_CONFIG_HOME}/docker"
export DOCKER_CONFIG

# GNUPG configuration
GNUPGHOME="${XDG_DATA_HOME}/gnupg"
export GNUPGHOME

# Go configuration
GOPATH="${XDG_DATA_HOME}/share/goexport"
export GOPATH

# GPG TTY
GPG_TTY="$(tty)"
export GPG_TTY

# Gradle XDG config
GRADLE_USER_HOME="${XDG_DATA_HOME}/gradle"
export GRADLE_USER_HOME

# GTK 1.0 configuration files
GTK_RC_FILES="${XDG_CONFIG_HOME}/gtk-1.0/gtkrc"
export GTK_RC_FILES

# GTK 2.0 configuration files
GTK2_RC_FILES="${XDG_CONFIG_HOME}/gtk-2.0/gtkrc"
export GTK2_RC_FILES

# K9s to follow XDG format
K9SCONFIG="${XDG_CONFIG_HOME}/k9s"
export K9SCONFIG

# NPM
NODE_REPL_HISTORY="$XDG_DATA_HOME"/node_repl_history
NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME"/npm/npmrc
export NODE_REPL_HISTORY
export NPM_CONFIG_USERCONFIG

# NUGET
NUGET_PACKAGES="${XDG_CACHE_HOME}/NuGetPackages"
export NUGET_PACKAGES

# NVM
export NVM_DIR="$XDG_DATA_HOME"/nvm

# PASS
PASSWORD_STORE_DIR="$XDG_DATA_HOME"/pass

# PSQL
PSQL_HISTORY="${XDG_STATE_HOME}/psql_history"
export PSQL_HISTORY

# Pylint configuration
PYLINTHOME="${XDG_CACHE_HOME}/pylint"
export PYLINTHOME

# RUST
CARGO_HOME="$XDG_DATA_HOME/cargo"
export CARGO_HOME

# SQLite history
SQLITE_HISTORY=$XDG_DATA_HOME/sqlite_history
export SQLITE_HISTORY

# Task warrior configuration
TASKRC="${XDG_CONFIG_HOME}/taskrc"
TASKDATA="${XDG_DATA_HOME}/task"
export TASKRC
export TASKDATA

# Terraform CLI config file
TF_CLI_CONFIG_FILE="${XDG_CONFIG_HOME}/terraformrc"
export TF_CLI_CONFIG_FILE

# TFLint configuration
TFLINT_PLUGIN_DIR="${XDG_DATA_HOME}/tflint.d"
export TFLINT_PLUGIN_DIR

# Tree Sitter
TREE_SITTER_DIR="${XDG_CONFIG_HOME}/tree-sitter"
export TREE_SITTER_DIR

# Vagrant XDG config
VAGRANT_HOME="${XDG_DATA_HOME}/vagrant"
VAGRANT_ALIAS_FILE="${XDG_DATA_HOME}/vagrant/aliases"
export VAGRANT_ALIAS_FILE
export VAGRANT_HOME

# WGET Configuration
WGETRC="$XDG_CONFIG_HOME/wgetrc"
export WGETRC

# WINE
export WINEPREFIX="${XDG_DATA_HOME}/wine/prefix"
export WINEPATH="${XDG_DATA_HOME}/wine"
export WINEARCH="win32"

# XAuthority file (this is completely ignored, sniff, sniff...)
XAUTHORITY="${XDG_RUNTIME_DIR}/Xauthority"

# Zoom data folder
export SSB_HOME="${XDG_DATA_HOME}"/zoom

# ZSH config directory
ZDOTDIR="${XDG_CONFIG_HOME}/zsh"
export ZDOTDIR

# ZSH Suggestions COLOR
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=245'
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE

