---
- name: Install which
  pacman:
    name: which
    state: present
  become: true
    
- name: Install base-devel tools
  pacman:
    name: base-devel
    state: present
  become: true

- name: Install basic network utils such as hostname
  pacman:
    name: inetutils
    state: present
  become: true

- name: Install ipcalc
  pacman:
    name: ipcalc
    state: present
  become: true

- name: Install Paru package manager
  aur: 
    name: paru

