---
- name: Installs Starship shell build
  kewlfft.aur.aur:
    use: paru
    name: starship
  when: ansible_distribution == "Archlinux"

- name: Make sure local config exists
  file:
    path: "{{ lookup('env','HOME') }}/.config"
    state: directory
    mode: '0700'

- name: Links config file for Starship
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/config/starship.toml"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.config/starship.toml"
    state: link
    force: yes

