---
- name: Installs Alacritty
  pacman:
    name: alacritty
    state: present
  become: true
  
- name: Links config file for Alacritty
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/config/alacritty"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.config/alacritty"
    state: link
    force: yes
