---
- name: Install `texlive` packages
  become: true
  pacman:
    name: texlive-basic
    state: present
  when: ansible_distribution == "Archlinux"

- name: Install `texlive-lang` packages
  become: true
  pacman:
    name: texlive-lang
    state: present
  when: ansible_distribution == "Archlinux"

- name: Install `texlive-bibtexextra` packages (Bibliography)
  become: true
  pacman:
    name: texlive-bibtexextra
    state: present
  when: ansible_distribution == "Archlinux"

- name: Install `biber` package (alternate Bibligraphy backend)
  become: true
  pacman:
    name: biber
    state: present
  when: ansible_distribution == "Archlinux"
