#! /bin/sh

# Launch shortcut daemon
sxhkd &

# Launch clipmenud
clipmenud &

# Launch Polybar
~/.config/polybar/launch.sh

# Set background image
feh --bg-fill /home/david/Pictures/somonstalenhag.se/l_ash09_big.jpg &

# Adding pulseaudio service startup
/usr/bin/start-pulseaudio-x11 & 

# Adding transparency
compton -f &

# Bluetooth Applet
blueman-applet &

bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10 

bspc config border_width         3 
bspc config window_gap          12

# Border colors
bspc config normal_border_color "#484848"
bspc config focused_border_color "#83a598"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"

bspc config top_padding          28
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# ScratchPad
st -c scratchterm &
bspc rule -a scratchterm sticky=on state=floating hidden=on
