#! /bin/sh

# Launch shortcut daemon
sxhkd &

# Launch clipmenud
clipmenud &

# Ensure dunst is our dbus deamon, in case other ones are installed and automatically started
/usr/bin/dunst &

# Set background image
feh --no-fehbg --bg-fill /home/david/Pictures/shaded_landscape.jpeg &
# feh --no-fehbg --bg-fill /home/david/Pictures/garden-house.png &

# Adding pulseaudio service startup
/usr/bin/start-pulseaudio-x11 &
# pulseaudio --start &
# /usr/bin/pactl load-module module-x11-publish "display=$DISPLAY xauthority=$XAUTHORITY" &

# Launch Polybar
~/.config/polybar/launch.sh

# Adding transparency
picom -b &

# Bluetooth
bluetoothctl power on
# blueman-applet &

# Configure the desktops for the laptop display
display_name="$(bspc query -M --names | head -1)"
bspc monitor "$display_name" -d 1 2 3 4 5 6 7 8 9 10
bspc config border_width         3
bspc config window_gap          12

# Border colors
bspc config normal_border_color "#332e41"
bspc config focused_border_color "#f9c096"
bspc config urgent_border_color "#e38c8f"
bspc config presel_border_color "#a4b9ef"

bspc config top_padding          28
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#adwaita-icon-theme ScratchPad
# st -c scratchterm &
# bspc rule -a scratchterm sticky=on state=floating hidden=on

bspc rule -a Zathura state=tiled
bspc rule -a Peek state=floating
