---
- name: Links .xinitrc file in HOME
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/roles/X11/files/.xinitrc"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.xinitrc"
    state: link
    force: yes
- name: Links .Xresources file in HOME
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/roles/X11/files/.Xresources"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.Xresources"
    state: link
    force: yes
- name: Add Benq SW320 XOrg configuration
  become: yes
  copy:
    src: "{{ lookup('env', 'ROOTDIR') }}/roles/X11/files/21-benq-sw320.conf"
    dest: "/etc/X11/xorg.conf.d/21-benq-sw320.conf"
    owner: root
    group: root
    mode: '0644'
