---
- name: Ensure nvim normal package is not installed
  become: true
  pacman:
    name: neovim
    state: absent
  when: ansible_distribution == "Archlinux"

- name: Telescope uses this tool to show files previews
  become: true
  pacman:
    name: bat
    state: present
  when: ansible_distribution == "Archlinux"

- name: Ensure pip is installed
  become: true
  pacman:
    name: python-pip
    state: present
  when: ansible_distribution == "Archlinux"

- name: Install ripgrep for complete project searchs
  become: true
  pacman:
    name: ripgrep
    state: present
  when: ansible_distribution == "Archlinux"

- name: Install for telescope to find files
  become: true
  pacman:
    name: fd
    state: present
  when: ansible_distribution == "Archlinux"

- name: Install tree-sitter
  become: true
  pacman:
    name: tree-sitter
    state: present
  when: ansible_distribution == "Archlinux"

- name: Ensure libterm01 does not exists
  become: true
  pacman:
    name: libvterm01
    state: absent
  when: ansible_distribution == "Archlinux"

- name: Install libvterm
  become: true
  pacman:
    name: libvterm
    state: present
  when: ansible_distribution == "Archlinux"

- name: Install python-setuptools
  become: true
  pacman:
    name: python-setuptools
    state: present
  when: ansible_distribution == "Archlinux"

- name: Installs nvim nightly build
  kewlfft.aur.aur:
    use: paru
    name: neovim-git
  when: ansible_distribution == "Archlinux"

- name: Links config file for nvim
  file:
    src: "{{ lookup('env', 'ROOTDIR') }}/files/config/nvim"
    dest: "{{ lookup( 'env', 'HOME' ) }}/.config/nvim"
    state: link
    force: yes

- name: Make sure nvim log folder exists
  ansible.builtin.file:
    path: "{{ lookup( 'env', 'HOME' ) }}/.local/share/nvim/log"
    state: directory
    mode: '0755'

- name: Make sure the tree-sitter teal folder exist
  ansible.builtin.file:
    path: "{{ lookup( 'env', 'HOME' ) }}/.local/share/nvim/tree-sitter-teal"
    state: directory
    mode: '0755'

- name: Make sure nvim start folder exists
  ansible.builtin.file:
    path: "{{ lookup( 'env', 'HOME' ) }}/.local/share/nvim/site/pack/packer/start"
    state: directory
    mode: '0755'

- name: Install packer
  ansible.builtin.git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: "{{ lookup( 'env', 'HOME' ) }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
