---
- name: Installs Newsboat RSS reader
  pacman:
    name: newsboat
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Installs Newsboat RSS reader
  apt:
    name: newsboat
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Installs urlscan
  pacman:
    name: urlscan
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Installs urlscan
  apt:
    name: urlscan
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Make sure cache Newsboat folder exists
  ansible.builtin.file:
    path: "{{ lookup( 'env', 'HOME' ) }}/.cache/newsboat"
    state: directory
    mode: '0755'

- name: Make sure config Newsboat folder exists
  ansible.builtin.file:
    path: "{{ lookup( 'env', 'HOME' ) }}/.config/newsboat"
    state: directory
    mode: '0755'

- name: Ensure Newsboat is configured
  template:
    src: config.j2
    dest: ~/.config/newsboat/config
